name: delete-old-packages
on:
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@508f6970a5f85097117972847749c79e0a276b26
        with: 
            owner: NamrataJha
            repo: test-repo
            package-name: test-repo
            min-versions-to-keep: 50

 


          
