name: delete-old-packages
on:
  registry_package:
    types: [published]
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@d846be5128e29a5e0be82504033990775c5fb1bc
        with: 
            owner: NamrataJha
            repo: test-repo
            package-name: test-repo
            num-old-versions-to-delete: 110

 


          
