name: delete-old-packages
on:
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        node: ['test-repo']
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@355299fa7da7483d87bd9c992f2a0adb60f7551c
        with: 
            owner: NamrataJha
            repo: test-repo
            package-name: ${{ matrix.node }}
            num-old-versions-to-delete: 150
            ignore-versions: "^(0|[1-9]\\d*)\\.0\\.0$"

 


          
