name: delete-old-packages
on:
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@1a7a0291b8a2e8b96794bfb7cc7da2cef0509203
        with: 
            owner: NamrataJha
            repo: test-repo
            package-name: test-repo
            min-versions-to-keep: 10
      - name: Delete package
        uses: actions/delete-package-versions@1a7a0291b8a2e8b96794bfb7cc7da2cef0509203
        with: 
            owner: NamrataJha
            repo: test-repo
            package-name: test-repo
            min-versions-to-keep: 10
      - name: Delete package
        uses: actions/delete-package-versions@1a7a0291b8a2e8b96794bfb7cc7da2cef0509203
        with: 
            owner: NamrataJha
            repo: test-repo
            package-name: test-repo
            min-versions-to-keep: 10

 


          
